-- SCHEMA COMPLET : PLANNING, COACHS & CONCEPTS
-- À exécuter dans l'éditeur SQL de Supabase (SQL Editor > New Query)

-- 1. Table COACHES
CREATE TABLE IF NOT EXISTS coaches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  bio TEXT,
  specialties TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Table COACH_AVAILABILITIES
CREATE TABLE IF NOT EXISTS coach_availabilities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coach_id BIGINT REFERENCES coaches(id) ON DELETE CASCADE,
  day TEXT NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Table COURSE_CONCEPTS
CREATE TABLE IF NOT EXISTS course_concepts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  type TEXT CHECK (type IN ('small_group', 'personal')),
  duration INTEGER DEFAULT 60,
  intensity INTEGER DEFAULT 3,
  capacity INTEGER DEFAULT 15,
  allowed_sales_types TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. MISE À JOUR Table CLASSES
ALTER TABLE classes 
ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'small_group' CHECK (type IN ('small_group', 'personal_training')),
ADD COLUMN IF NOT EXISTS concept_id BIGINT REFERENCES course_concepts(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS coach_id BIGINT REFERENCES coaches(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS intensity INTEGER;

-- 5. POLITIQUES DE SÉCURITÉ (RLS) - Accès public pour le développement
ALTER TABLE coaches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access to coaches" ON coaches;
CREATE POLICY "Public access to coaches" ON coaches FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE coach_availabilities ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access to coach_availabilities" ON coach_availabilities;
CREATE POLICY "Public access to coach_availabilities" ON coach_availabilities FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE course_concepts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access to course_concepts" ON course_concepts;
CREATE POLICY "Public access to course_concepts" ON course_concepts FOR ALL USING (true) WITH CHECK (true);
