-- Migration Expansion : Planning Avançé et Concepts de cours
-- À exécuter dans l'éditeur SQL de Supabase

-- 1. Table COACHES
CREATE TABLE IF NOT EXISTS coaches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  bio TEXT,
  specialties TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Table COACH_AVAILABILITIES (Disponibilités hebdomadaires types)
CREATE TABLE IF NOT EXISTS coach_availabilities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coach_id BIGINT REFERENCES coaches(id) ON DELETE CASCADE,
  day TEXT NOT NULL, -- Lundi, Mardi, etc.
  start_time TEXT NOT NULL, -- HH:mm
  end_time TEXT NOT NULL, -- HH:mm
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Table COURSE_CONCEPTS (Fiches descriptives)
CREATE TABLE IF NOT EXISTS course_concepts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  type TEXT CHECK (type IN ('small_group', 'personal')),
  duration INTEGER DEFAULT 60, -- En minutes
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. MISE À JOUR Table CLASSES
-- On ajoute le type et le lien vers le concept et le coach
ALTER TABLE classes 
ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'small_group' CHECK (type IN ('small_group', 'personal_training')),
ADD COLUMN IF NOT EXISTS concept_id BIGINT REFERENCES course_concepts(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS coach_id BIGINT REFERENCES coaches(id) ON DELETE SET NULL;

-- 5. POLITIQUES DE SÉCURITÉ (RLS)
ALTER TABLE coaches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public access to coaches" ON coaches FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE coach_availabilities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public access to coach_availabilities" ON coach_availabilities FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE course_concepts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public access to course_concepts" ON course_concepts FOR ALL USING (true) WITH CHECK (true);

-- 6. DONNÉES DE DÉMONSTRATION (Optionnel)
INSERT INTO coaches (name, bio, specialties) VALUES 
  ('Alex Johnson', 'Expert en force et conditionnement physique.', 'Crossfit, Powerlifting'),
  ('Sarah Miller', 'Coach passionnée de mobilité et bien-être.', 'Yoga, Pilates');
