-- SCHEMA NOTIFICATIONS
-- À exécuter dans l'éditeur SQL de Supabase

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, -- Ou BIGINT si lié à la table members
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT CHECK (type IN ('confirmation', 'reminder', 'system')),
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Si la table members utilise des ID BIGINT personnalisés au lieu des UUID auth.users :
-- ALTER TABLE notifications ALTER COLUMN member_id TYPE BIGINT;
-- ALTER TABLE notifications ADD CONSTRAINT notifications_member_id_fkey FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE;

-- POLITIQUES DE SÉCURITÉ (RLS)
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Les membres peuvent voir leurs propres notifications" ON notifications;
CREATE POLICY "Les membres peuvent voir leurs propres notifications" 
ON notifications FOR SELECT 
USING (auth.uid() = member_id);

DROP POLICY IF EXISTS "Système/Admin peuvent créer des notifications" ON notifications;
CREATE POLICY "Système/Admin peuvent créer des notifications" 
ON notifications FOR INSERT 
WITH CHECK (true); -- En production, restraindre à un service_role ou trigger

DROP POLICY IF EXISTS "Les membres peuvent marquer comme lu" ON notifications;
CREATE POLICY "Les membres peuvent marquer comme lu" 
ON notifications FOR UPDATE 
USING (auth.uid() = member_id)
WITH CHECK (auth.uid() = member_id);
