-- Migration : Initialisation des tables Club Connect pour Supabase

-- 1. Table MEMBERS
CREATE TABLE IF NOT EXISTS members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  plan TEXT,
  status TEXT,
  joined TEXT,
  avatar INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Table TRANSACTIONS
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
  amount NUMERIC,
  date TEXT,
  status TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Table EXERCISES
CREATE TABLE IF NOT EXISTS exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  muscle TEXT,
  type TEXT,
  equipment TEXT,
  difficulty TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Table SESSIONS (Contient des objets JSON pour les exercices de la séance)
CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  exercises JSONB DEFAULT '[]'::JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Table PROGRAMS (Contient des tableaux JSON pour le planning et l'assignation)
CREATE TABLE IF NOT EXISTS programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  level TEXT,
  duration TEXT,
  assigned_to JSONB DEFAULT '[]'::JSONB,
  schedule JSONB DEFAULT '[]'::JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ==========================================
-- POLITIQUES DE SÉCURITÉ (RLS)
-- Attention : En mode développement, nous ouvrons les accès. A restreindre avant le vrai lancement en production.
-- ==========================================

ALTER TABLE members ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access to members" ON members;
CREATE POLICY "Public access to members" ON members FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access to transactions" ON transactions;
CREATE POLICY "Public access to transactions" ON transactions FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE exercises ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access to exercises" ON exercises;
CREATE POLICY "Public access to exercises" ON exercises FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access to sessions" ON sessions;
CREATE POLICY "Public access to sessions" ON sessions FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE programs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access to programs" ON programs;
CREATE POLICY "Public access to programs" ON programs FOR ALL USING (true) WITH CHECK (true);
